export const USER_LOGIN = "USER_LOGIN";
export const USER_LOGIN_SUCCESS = "USER_LOGIN_SUCCESS";
export const USER_LOGIN_FAILURE = "USER_LOGIN_FAILURE";
export const USER_LOGOUT = "USER_LOGOUT";

export const ZABOES_LIST = "ZABOES_LIST";
export const ZABOES_RESET = "ZABOES_RESET";
export const ZABOES_PAGECOUNT = "ZABOES_PAGECOUNT";
export const ZABO_SEARCH = "ZABO_SEARCH";
export const ZABO_DELETE = "ZABO_DELETE";
export const ZABO_UPDATE = "ZABO_UPDATE";
export const GET_PARTICIPATED_ZABOES = "GET_PARTICIPATED_ZABOES";
export const SET_CURRENT_USER = "SET_CURRENT_USER";
export const SET_NOTIFICATIONS = "SET_NOTIFICATIONS";
export const SET_CREATED_ZABOES = "SET_CREATED_ZABOES";

export const GOT_RESPONSE = "GOT_RESPONSE";
export const START_AJAX = "START_AJAX";

export const LOGOUT = "LOGOUT";
export const LOGIN = "LOGIN";
export const SET_LANG = "SET_LANG";
export const CATEGORY_ZABOES_RESET = "CATEGORY_ZABOES_RESET";
