export const USER_LOGIN = "USER_LOGIN";
export const USER_LOGIN_SUCCESS = "USER_LOGIN_SUCCESS";
export const USER_LOGIN_FAILURE = "USER_LOGIN_FAILURE";
export const USER_LOGOUT = "USER_LOGOUT";

export const ZABOES_LIST = "ZABOES_LIST";
export const ZABOES_PAGECOUNT = "ZABOES_PAGECOUNT";
export const ZABO_CREATE = "ZABO_CREATE";
export const ZABO_DELETE = "ZABO_DELETE";
export const ZABO_UPDATE = "ZABO_UPDATE";
export const GET_PARTICIPATED_ZABOES = "ZABO_PARTICIPATED_ZABOES";
export const LOGOUT = "LOGOUT";
export const LOGIN = "LOGIN";
export const SET_LANG = "SET_LANG";
export const MAIN_ZABO_SEEN = "MAIN_ZABO_SEEN";
